### ISSUE TITLE
How to get the vulnerable source code of cves in the dataset

### ISSUE THREAD

**Issue by zifeng-kang** [tuhh-softsec/vul4j#10]
Hi, 

Nice work and I love your dataset! I am wondering if I can get a json containing the cve together with its vulnerable source code, and patch code from your dataset. Is the code-level information available? Thanks!

**Comment by bqcuong** [comment]
Hi,

Did you take a look at the dataset csv file?
[dataset/vul4j_dataset.csv](dataset/vul4j_dataset.csv)

Best,
Cuong

**Comment by zifeng-kang** [comment]
Thanks for the reply. However, I did not see the source code part as I expected. I was hoping e.g., `
public class Issue1005 extends TestCase {
    public void test_for_issue() throws Exception {
        Model model = JSON.parseObject("{\"values\":[1,2,3]}", Model.class);`
I can only get those source codes after visiting the github links and copy codes from it.

**Comment by bqcuong** [comment]
We do not provide directly such source code. But I think they can be obtained from the patches with a small script.
Cheers.
