### ISSUE TITLE
License for the data?

### ISSUE THREAD

**Issue by pombredanne** [tuhh-softsec/vul4j#8]
Hi:
What is the license for your data?
I would like to include these in VulnerableCode https://github.com/nexB/vulnerablecode/issues/1269
GPL is not really a license for data... what about using a CC-BY or CC-BY-SA?
Thank you!

**Comment by bqcuong** [comment]
Hi,

You are welcome to use my dataset in any way.
I've licensed the dataset under CC-BY in the repository.
Please feel free to use it.

Best,
Cuong
