### ISSUE TITLE
vul4j checkout wipes local changes in the original git repo

### ISSUE THREAD

**Issue by wtwhite** [tuhh-softsec/vul4j#9]
After cloning, editing paths in [vul4j/config.py](https://github.com/tuhh-softsec/vul4j/blob/main/vul4j/config.py), installing (locally via `pip install .` as suggested [here](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary)), and then running `vul4j checkout --id VUL4J-10 -d /tmp/vul4j/VUL4J-10` per the example in the README, I was surprised to find that my local edits to `vul4j/config.py` in the original cloned work tree had been reverted.

It seems this is done on purpose: https://github.com/tuhh-softsec/vul4j/blob/main/vul4j/main.py#L175. This is surprising behaviour and took me a while to debug. Is it necessary? If all you actually want `vul4j checkout` to do is create a checked-out work tree of the given vuln in the destination folder, I'm happy to contribute a PR for this. ([The basic idea is to specify `--work-tree` to `git checkout`.](https://stackoverflow.com/a/16493707/47984))

It would also be nice to mention the unusual branch layout (namely one `VUL4J-nn` branch per vuln, with totally different contents from `main`) in the README.

**Comment by bqcuong** [comment]
Hi,

It would be greatly appreciated for a pull request on this.

Best,
Cuong
